### ISSUE TITLE
No Module found

### ISSUE THREAD

**Issue by mackreal** [yretenai/io_import_pskx#1]
```
Traceback (most recent call last):
File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.0\scripts\modules\addon_utils.py", line 351, in enable
mod = _import_(module_name)
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_pskx-develop\_init__.py", line 39, in <module>
from io_import_pskx import op
ModuleNotFoundError:
No module named 'io_import_pskx'
```

I followed the instructions as specified but I was greeted with this error, not sure what I did wrong.

**Comment by b1naryTR** [comment]
Yeap, same here.

**Comment by neptuwunium** [comment]
Reinstall the addon, but remove `-develop` from the zip filename. Alternatively go to the addons folder and remove `-develop` from the folder name and activate it again in blender. That _should_ fix it.

I don't know why people are using this addon though, nothing exports to these modified formats (aside from my unstable fork.)

**Comment by Madlykeanu** [comment]
i removed -develop from the folder name and still got the same error,

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ksorc\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_pskx-develop\__init__.py", line 39, in <module>
    from io_import_pskx import op
ModuleNotFoundError: No module named 'io_import_pskx'

**Comment by neptuwunium** [comment]
are you sure?

>  "C:\Users\ksorc\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_import_pskx **-develop** _init_.py"

**Comment by 4rtb** [comment]
I had the same mistake, thanks to yretenai for solving it
