### ISSUE TITLE
Issue Importing PSK / PSA

### ISSUE THREAD

**Issue by SanityVisuals** [yretenai/io_import_pskx#2]
Python: Traceback (most recent call last):
  File "C:\Users\Liqui\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_pskx\op\op_import_psa.py", line 47, in execute
    if ActorXAnimation(path, settings).execute(context) == {'FINISHED'}:
  File "C:\Users\Liqui\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_pskx\blend\psa.py", line 44, in execute
    return self.execute_legacy(context)
  File "C:\Users\Liqui\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_pskx\blend\psa.py", line 143, in execute_legacy
    bone_map: dict[str, Bone] = {bone['actorx:full_bone_name']: bone for bone in armature_data.bones}
  File "C:\Users\Liqui\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_import_pskx\blend\psa.py", line 143, in <dictcomp>
    bone_map: dict[str, Bone] = {bone['actorx:full_bone_name']: bone for bone in armature_data.bones}
KeyError: 'bpy_struct[key]: key "actorx:full_bone_name" not found'

This is the error that is being Thrown by Blenders info log! 

Just wondering if I'm doing something wrong!

**Comment by egeodabasi10** [comment]
I seem to have the same issue.
Were you able to find a solution to this?

**Comment by neptuwunium** [comment]
This happens when you're trying to load an animation to a skeleton not imported by the same addon. I suggest using https://github.com/DarklightGames/io_scene_psk_psa instead, this addon was mostly made for my own tests with unofficial edits to the format.

In other words, make sure you have an armature selected that's imported by this addon, _or_ deselect the armature.

**Comment by 4rtb** [comment]
I got errors too, when I tried to import psk into blender scene and when I tried to import psa motion for skeleton, it separated the skeleton from the mesh and imposed an action rather than attaching it to the selected one (skeleton)

Video
[26.02.2024 09_47.webm](https://github.com/yretenai/io_import_pskx/assets/141040913/7ab520ee-6de8-4a93-b0f7-331ce02dfe22)

Logs
Read prefs: "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
[WORLD] trying to load ue_format for uemodel support
[WORLD] failed to load ue_format
Info: Deleted 3 object(s)

[ACTORX] No parser found for ACTRHEAD!
[ACTORX] No parser found for MRPHINFO!
[ACTORX] No parser found for MRPHDATA!
Traceback (most recent call last):
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_pskx\op\op_import_psk.py", line 48, in execute
    if ActorXMesh(path, settings).execute(context) == {'FINISHED'}:
  File "C:\Users\tewald\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_pskx\blend\psk.py", line 69, in execute
    mesh_data.normals_split_custom_set_from_vertices(self.psk.Normals)
TypeError: Mesh.normals_split_custom_set_from_vertices(): error with argument 1, "normals" -  expected a sequence of float, not NoneType

P.S. I tried to do it by using blender 4.0, but situation was the same

**Comment by neptuwunium** [comment]
this addon is not made for the updated pskx format, it's for my own edits to the format.

**Comment by neptuwunium** [comment]
psk/psa is no longer supported at all, [use the normal importer](https://github.com/DarklightGames/io_scene_psk_psa)
